/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function encryptVote(pubKeyBytes: Buffer, choice: number, optionsCount: number): string
export function eccEncrypt(pk: Buffer, msg: Buffer): Buffer
export function eccDecrypt(sk: Buffer, encrypted: Buffer): Buffer
export interface ExportedKeyPair {
  public: string
  secret: string
}
export function generateRsaKeypair(): ExportedKeyPair
export function sign(secretKeyPem: string, blindMsg: Buffer): Buffer
export function verify(publicKeyPem: string, signatureBytes: Buffer, msgRandomizer: Buffer, msg: string): boolean
