/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function generateElgamalKeypair(): ExportedKeyPair
export declare function encryptVote(pubKeyBytes: Buffer, choice: number, optionsCount: number): Buffer
export declare function eccEncrypt(pk: Buffer, msg: Buffer): Buffer
export declare function eccDecrypt(sk: Buffer, encrypted: Buffer): Buffer
export interface ExportedBlindingResult {
  blindMsg: Buffer
  secret: Buffer
}
export declare function createRequest(publicKey: Buffer, clientAddr: string, iatDelay: number, electionId: string): ExportedBlindingResult
export declare function generateRsaKeypair(): ExportedKeyPair
export declare function sign(secretKey: Buffer, blindMsg: Buffer): Buffer
export declare function unblind(publicKey: Buffer, secret: Buffer, blindSig: Buffer, clientAddr: string, iatDelay: number, electionId: string): Buffer
export declare function verify(publicKey: Buffer, signatureBytes: Buffer, msg: Buffer): void
export interface ExportedKeyPair {
  public: Buffer
  private: Buffer
}
